# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Anirudh
description:      'I work as a software developer at Flipkart. This is my personal blog, any views expressed here are solely mine.'
url:              https://anirudhramanan.com
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Anirudh Ramanan'

paginate:         10

disqus_shortname: anirudh

github:
  repo:           https://github.com/anirudhramanan/anirudhramanan.github.io

gems:
  - jekyll-sitemap
  - jemoji

twitter: '@anirudh_ramanan'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
