# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Anirudh Ramanan
description:      'I work as a Software Developer at Flipkart. This is my personal blog and any views expressed here are solely mine. And yea, Proud to be Udacity Nanodegree Graduate'
url:              http://iamanirudh.com
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Anirudh Ramanan'
  url:            https://plus.google.com/107972823913344955047

paginate:         5

disqus_shortname: anirudh

github:
  repo:           https://github.com/anirudhramanan/anirudhramanan.github.io

gems:
  - jekyll-sitemap

twitter: '@i_anirudh23'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
