# Site settings
title: Anirudh Ramanan # site title
lang: en-US # default lang
timezone: Asia/Mumbai # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Anirudh Ramanan # author name
  bio: I'm a software engineer at <b><a href="https://nextleap.app" target="_blank">Nextleap</a></b>. This is my personal space and any views expressed here are mine, and solely mine.
  connect:
     github: fork<b><a href="https://github.com/anirudhramanan" target="_blank">@Github</a></b>
     linkedin: network<b><a href="https://www.linkedin.com/in/anirudhramanan" target="_blank">@LinkedIn</a></b>
     twitter: mention<b><a href="https://twitter.com/imanirudhr" target="_blank">@Twitter</a></b>
  github: anirudhramanan # github username
  twitter: imanirudhr # twitter username
  email: anirudhramanan23@gmail.com # email adress
  avatar: /assets/img/profile.png # change with your own avatar

# URL settings
url: "https://anirudh.xyz" #
baseurl:
permalink: /:title/
google_analytics: UA-75865495-1

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
# markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false


# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github: [metadata]
