# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Anirudh
description:      'I work as a Software Developer at Flipkart. This is my personal blog and any views expressed here are solely mine.'
url:              https://www.anirudh.xyz
baseurl:          /
logo:             /content/icons/icon.jpg

author:
  name:           'Anirudh Ramanan'

paginate:         10

disqus_shortname: anirudh

github:
  repo:           https://github.com/anirudhramanan/anirudhramanan.github.io

gems:
  - jekyll-sitemap
  - jemoji

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
